
#
#Noel Rafferty
#
#As COMPUTER SCIENCE


def three:
    pass
except Exception as e:
    print("Error Occured:", e)

def two:
    pass
except Exception as e:
    print("Error Occured:", e)

def one():
    pass
except Exception as e:
    print("Error Occured:", e)


def main():
    try:


    
    pass
except Exception as e:
    print("Error Occured:", e)
if(__name__ == "__main__"):
    main()


